main: de.jumpstone.plugins.HMTSync
version: 2.1.1
name: HMTSync
author: jumpstone
api-version: 1.21
permissions:
  hmtsync.admin:
    description: Allows use of admin commands for HMT Sync
    default: op
commands:
  hmtsync:
    description: Main command for HMT Sync
    usage: /hmtsync <subcommand>
    permission: hmtsync.admin
  hmtsync-debug:
    description: Debug command for HMT Sync
    usage: /hmtsync-debug <subcommand>
    permission: hmtsync.admin