main: com.digitalserverhost.plugins.MCDataBridge
version: 2.1.1-SNAPSHOT
name: mc-data-bridge
author: DigitalServerHost
api-version: 1.21
permissions:
  databridge.admin:
    description: Allows use of admin commands for MC Data Bridge
    default: op
commands:
  databridge:
    description: Main command for MC Data Bridge
    usage: /databridge <subcommand>
    permission: databridge.admin